### ISSUE TITLE
Github Actions

### ISSUE THREAD

**Issue by wit3** [WilberGroup/airdrop#12]
Hi, when i try to use deploy with Github Actions and make new deploy.yml file in workflow folder

the github action when push file on my repo fail because not found artisan
`
PHP Warning:  require(/home/runner/work/xxxx/yyyyy/vendor/autoload.php): Failed to open stream: No such file or directory in /home/runner/work/xxxx/yyyyy/artisan on line 18`

```yml
name: Laravel ASSETS

on:
  push:
    branches: [staging]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Generate Airdrop Hash
        run: echo "AIRDROP_HASH=$(php artisan airdrop:hash)" >> $GITHUB_ENV
      - name: Cache Airdrop Assets
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-airdrop-${{ env.AIRDROP_HASH }}
          path: /tmp/airdrop-*

```
